# Generated by Django 2.2.4 on 2019-08-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_usermembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='UserMembership',
        ),
    ]
