export const ERROR_ALERT = "ERROR_ALERT";
export const FETCHING_DATA = "FETCHING_DATA";

export const USER_AUTH_FAIL = "USER_AUTH_FAIL";
export const USER_AUTH_LOGOUT = "USER_AUTH_LOGOUT";
export const USER_AUTH_START = "USER_AUTH_START";
export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS";

export const CREATE_TICKET = "CREATE_TICKET";
export const RECEIVE_TICKET = "RECEIVE_TICKET";
export const RECEIVE_TICKETS_LIST = "RECEIVE_TICKETS_LIST";
export const UPDATED_TICKET_VOTE = "UPDATED_TICKET_VOTE";

export const FETCH_TICKET_DETAIL = "FETCH_TICKET_DETAIL";
export const RECEIVE_TICKET_DETAIL = "RECEIVE_TICKET_DETAIL";

export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const GET_ERRORS = "GET_ERRORS";

export const FETCHING_USER = "FETCHING_USER";
export const RECEIVED_USER = "RECEIVED_USER";
export const RECEIVED_USER_PROFILE = "RECEIVED_USER_PROFILE";
export const FETCHING_USER_PROFILE = "FETCHING_USER_PROFILE";

export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

export const RECEIVE_MEMBERSHIPS_LIST = "RECEIVE_MEMBERSHIPS_LIST";
