export const PaymentMethods = [
  { key: "st", value: "st", text: "Stripe" },
  { key: "pp", value: "pp", text: "Paypal" }
];

export const Countries = [
  { text: "Afghanistan", value: "af" },
  { text: "Aland Islands", value: "ax" },
  { text: "Albania", value: "al" },
  { text: "Algeria", value: "dz" },
  { text: "American Samoa", value: "as" },
  { text: "Andorra", value: "ad" },
  { text: "Angola", value: "ao" },
  { text: "Anguilla", value: "ai" },
  { text: "Antigua", value: "ag" },
  { text: "Argentina", value: "ar" },
  { text: "Armenia", value: "am" },
  { text: "Aruba", value: "aw" },
  { text: "Australia", value: "au" },
  { text: "Austria", value: "at" },
  { text: "Azerbaijan", value: "az" },
  { text: "Bahamas", value: "bs" },
  { text: "Bahrain", value: "bh" },
  { text: "Bangladesh", value: "bd" },
  { text: "Barbados", value: "bb" },
  { text: "Belarus", value: "by" },
  { text: "Belgium", value: "be" },
  { text: "Belize", value: "bz" },
  { text: "Benin", value: "bj" },
  { text: "Bermuda", value: "bm" },
  { text: "Bhutan", value: "bt" },
  { text: "Bolivia", value: "bo" },
  { text: "Bosnia", value: "ba" },
  { text: "Botswana", value: "bw" },
  { text: "Bouvet Island", value: "bv" },
  { text: "Brazil", value: "br" },
  { text: "British Virgin Islands", value: "vg" },
  { text: "Brunei", value: "bn" },
  { text: "Bulgaria", value: "bg" },
  { text: "Burkina Faso", value: "bf" },
  { text: "Burma", value: "mm", alias: "Myanmar" },
  { text: "Burundi", value: "bi" },
  { text: "Caicos Islands", value: "tc" },
  { text: "Cambodia", value: "kh" },
  { text: "Cameroon", value: "cm" },
  { text: "Canada", value: "ca" },
  { text: "Cape Verde", value: "cv" },
  { text: "Cayman Islands", value: "ky" },
  { text: "Central African Republic", value: "cf" },
  { text: "Chad", value: "td" },
  { text: "Chile", value: "cl" },
  { text: "China", value: "cn" },
  { text: "Christmas Island", value: "cx" },
  { text: "Cocos Islands", value: "cc" },
  { text: "Colombia", value: "co" },
  { text: "Comoros", value: "km" },
  { text: "Congo", value: "cd" },
  { text: "Congo Brazzaville", value: "cg" },
  { text: "Cook Islands", value: "ck" },
  { text: "Costa Rica", value: "cr" },
  { text: "Cote Divoire", value: "ci" },
  { text: "Croatia", value: "hr" },
  { text: "Cuba", value: "cu" },
  { text: "Cyprus", value: "cy" },
  { text: "Czech Republic", value: "cz" },
  { text: "Denmark", value: "dk" },
  { text: "Djibouti", value: "dj" },
  { text: "Dominica", value: "dm" },
  { text: "Dominican Republic", value: "do" },
  { text: "Ecuador", value: "ec" },
  { text: "Egypt", value: "eg" },
  { text: "El Salvador", value: "sv" },
  { text: "Equatorial Guinea", value: "gq" },
  { text: "Eritrea", value: "er" },
  { text: "Estonia", value: "ee" },
  { text: "Ethiopia", value: "et" },
  { text: "Europeanunion", value: "eu" },
  { text: "Falkland Islands", value: "fk" },
  { text: "Faroe Islands", value: "fo" },
  { text: "Fiji", value: "fj" },
  { text: "Finland", value: "fi" },
  { text: "France", value: "fr" },
  { text: "French Guiana", value: "gf" },
  { text: "French Polynesia", value: "pf" },
  { text: "French Territories", value: "tf" },
  { text: "Gabon", value: "ga" },
  { text: "Gambia", value: "gm" },
  { text: "Georgia", value: "ge" },
  { text: "Germany", value: "de" },
  { text: "Ghana", value: "gh" },
  { text: "Gibraltar", value: "gi" },
  { text: "Greece", value: "gr" },
  { text: "Greenland", value: "gl" },
  { text: "Grenada", value: "gd" },
  { text: "Guadeloupe", value: "gp" },
  { text: "Guam", value: "gu" },
  { text: "Guatemala", value: "gt" },
  { text: "Guinea", value: "gn" },
  { text: "Guinea-Bissau", value: "gw" },
  { text: "Guyana", value: "gy" },
  { text: "Haiti", value: "ht" },
  { text: "Heard Island", value: "hm" },
  { text: "Honduras", value: "hn" },
  { text: "Hong Kong", value: "hk" },
  { text: "Hungary", value: "hu" },
  { text: "Iceland", value: "is" },
  { text: "India", value: "in" },
  { text: "Indian Ocean Territory", value: "io" },
  { text: "Indonesia", value: "id" },
  { text: "Iran", value: "ir" },
  { text: "Iraq", value: "iq" },
  { text: "Ireland", value: "ie" },
  { text: "Israel", value: "il" },
  { text: "Italy", value: "it" },
  { text: "Jamaica", value: "jm" },
  { text: "Jan Mayen", value: "sj", alias: "Svalbard" },
  { text: "Japan", value: "jp" },
  { text: "Jordan", value: "jo" },
  { text: "Kazakhstan", value: "kz" },
  { text: "Kenya", value: "ke" },
  { text: "Kiribati", value: "ki" },
  { text: "Kuwait", value: "kw" },
  { text: "Kyrgyzstan", value: "kg" },
  { text: "Laos", value: "la" },
  { text: "Latvia", value: "lv" },
  { text: "Lebanon", value: "lb" },
  { text: "Lesotho", value: "ls" },
  { text: "Liberia", value: "lr" },
  { text: "Libya", value: "ly" },
  { text: "Liechtenstein", value: "li" },
  { text: "Lithuania", value: "lt" },
  { text: "Luxembourg", value: "lu" },
  { text: "Macau", value: "mo" },
  { text: "Macedonia", value: "mk" },
  { text: "Madagascar", value: "mg" },
  { text: "Malawi", value: "mw" },
  { text: "Malaysia", value: "my" },
  { text: "Maldives", value: "mv" },
  { text: "Mali", value: "ml" },
  { text: "Malta", value: "mt" },
  { text: "Marshall Islands", value: "mh" },
  { text: "Martinique", value: "mq" },
  { text: "Mauritania", value: "mr" },
  { text: "Mauritius", value: "mu" },
  { text: "Mayotte", value: "yt" },
  { text: "Mexico", value: "mx" },
  { text: "Micronesia", value: "fm" },
  { text: "Moldova", value: "md" },
  { text: "Monaco", value: "mc" },
  { text: "Mongolia", value: "mn" },
  { text: "Montenegro", value: "me" },
  { text: "Montserrat", value: "ms" },
  { text: "Morocco", value: "ma" },
  { text: "Mozambique", value: "mz" },
  { text: "Namibia", value: "na" },
  { text: "Nauru", value: "nr" },
  { text: "Nepal", value: "np" },
  { text: "Netherlands", value: "nl" },
  { text: "Netherlandsantilles", value: "an" },
  { text: "New Caledonia", value: "nc" },
  { text: "New Guinea", value: "pg" },
  { text: "New Zealand", value: "nz" },
  { text: "Nicaragua", value: "ni" },
  { text: "Niger", value: "ne" },
  { text: "Nigeria", value: "ng" },
  { text: "Niue", value: "nu" },
  { text: "Norfolk Island", value: "nf" },
  { text: "North Korea", value: "kp" },
  { text: "Northern Mariana Islands", value: "mp" },
  { text: "Norway", value: "no" },
  { text: "Oman", value: "om" },
  { text: "Pakistan", value: "pk" },
  { text: "Palau", value: "pw" },
  { text: "Palestine", value: "ps" },
  { text: "Panama", value: "pa" },
  { text: "Paraguay", value: "py" },
  { text: "Peru", value: "pe" },
  { text: "Philippines", value: "ph" },
  { text: "Pitcairn Islands", value: "pn" },
  { text: "Poland", value: "pl" },
  { text: "Portugal", value: "pt" },
  { text: "Puerto Rico", value: "pr" },
  { text: "Qatar", value: "qa" },
  { text: "Reunion", value: "re" },
  { text: "Romania", value: "ro" },
  { text: "Russia", value: "ru" },
  { text: "Rwanda", value: "rw" },
  { text: "Saint Helena", value: "sh" },
  { text: "Saint Kitts and Nevis", value: "kn" },
  { text: "Saint Lucia", value: "lc" },
  { text: "Saint Pierre", value: "pm" },
  { text: "Saint Vincent", value: "vc" },
  { text: "Samoa", value: "ws" },
  { text: "San Marino", value: "sm" },
  { text: "Sandwich Islands", value: "gs" },
  { text: "Sao Tome", value: "st" },
  { text: "Saudi Arabia", value: "sa" },
  { text: "Scotland", value: "gb sct" },
  { text: "Senegal", value: "sn" },
  { text: "Serbia", value: "cs" },
  { text: "Serbia", value: "rs" },
  { text: "Seychelles", value: "sc" },
  { text: "Sierra Leone", value: "sl" },
  { text: "Singapore", value: "sg" },
  { text: "Slovakia", value: "sk" },
  { text: "Slovenia", value: "si" },
  { text: "Solomon Islands", value: "sb" },
  { text: "Somalia", value: "so" },
  { text: "South Africa", value: "za" },
  { text: "South Korea", value: "kr" },
  { text: "Spain", value: "es" },
  { text: "Sri Lanka", value: "lk" },
  { text: "Sudan", value: "sd" },
  { text: "Suritext", value: "sr" },
  { text: "Swaziland", value: "sz" },
  { text: "Sweden", value: "se" },
  { text: "Switzerland", value: "ch" },
  { text: "Syria", value: "sy" },
  { text: "Taiwan", value: "tw" },
  { text: "Tajikistan", value: "tj" },
  { text: "Tanzania", value: "tz" },
  { text: "Thailand", value: "th" },
  { text: "Timorleste", value: "tl" },
  { text: "Togo", value: "tg" },
  { text: "Tokelau", value: "tk" },
  { text: "Tonga", value: "to" },
  { text: "Trinidad", value: "tt" },
  { text: "Tunisia", value: "tn" },
  { text: "Turvalue", value: "tr" },
  { text: "Turkmenistan", value: "tm" },
  { text: "Tuvalu", value: "tv" },
  { text: "U.A.E.", value: "ae", alias: "United Arab Emirates" },
  { text: "Uganda", value: "ug" },
  { text: "Ukraine", value: "ua" },
  { text: "United Kingdom", value: "gb", alias: "uk" },
  { text: "United States", value: "us", alias: "America" },
  { text: "Uruguay", value: "uy" },
  { text: "US Minor Islands", value: "um" },
  { text: "US Virgin Islands", value: "vi" },
  { text: "Uzbekistan", value: "uz" },
  { text: "Vanuatu", value: "vu" },
  { text: "Vatican City", value: "va" },
  { text: "Venezuela", value: "ve" },
  { text: "Vietnam", value: "vn" },
  { text: "Wales", value: "gb wls" },
  { text: "Wallis and Futuna", value: "wf" },
  { text: "Western Sahara", value: "eh" },
  { text: "Yemen", value: "ye" },
  { text: "Zambia", value: "zm" },
  { text: "Zimbabwe", value: "zw" }
];

export const unicornFreeServices = [
  "View Tickets",
  "Donations",
  "View bugs and features status"
];

export const unicornProServices = [
  "Donations",
  "View bugs and features status",
  "View tickets",
  "Create tickets",
  "Vote on tickets",
  "Comment on tickets",
  "Blog access"
];
