# Generated by Django 2.2.4 on 2019-09-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_membership',
            field=models.ManyToManyField(blank=True, to='memberships.Membership'),
        ),
    ]
