# Generated by Django 2.2.4 on 2019-09-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='is_subscribed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
