# Generated by Django 2.2.4 on 2019-08-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcription',
            old_name='user_membership',
            new_name='membership_user',
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_option',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Professional')], default='free', max_length=50),
        ),
    ]
