# Generated by Django 2.2.4 on 2019-09-11 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_usermembership_is_subscribed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermembership',
            old_name='is_subscribed',
            new_name='is_pro_subscribed',
        ),
    ]
