# Generated by Django 2.2.4 on 2019-08-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20190811_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcription',
            old_name='membership_user',
            new_name='user_membership',
        ),
    ]
