# Generated by Django 2.2.4 on 2019-08-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_auto_20190811_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_option',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Professional')], default='Free', max_length=50),
        ),
    ]
