# Generated by Django 2.2.4 on 2019-09-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_auto_20190911_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='date_added',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='date_subscribed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
