# Generated by Django 2.2.4 on 2019-09-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_auto_20190911_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermembership',
            old_name='is_pro_subscribed',
            new_name='is_subscribed',
        ),
        migrations.AddField(
            model_name='usermembership',
            name='date_subscribed',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
