# Generated by Django 2.2.4 on 2019-09-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_auto_20190913_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermembership',
            old_name='date_subscribed',
            new_name='date_signedup',
        ),
        migrations.RenameField(
            model_name='usermembership',
            old_name='is_subscribed',
            new_name='is_member',
        ),
    ]
