# Generated by Django 3.0 on 2019-12-11 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('subject', models.CharField(max_length=120)),
                ('tag', models.SlugField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To-do'), ('doing', 'Doing'), ('done', 'Done'), ('backlog', 'Backlog')], default='todo', max_length=7)),
                ('is_bug', models.BooleanField(default=False)),
                ('is_feature', models.BooleanField(default=False)),
                ('has_solution', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=5, null=True)),
                ('views', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=200, null=True)),
                ('owner', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('votes', models.ManyToManyField(blank=True, related_name='ticket_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField()),
                ('status', models.CharField(choices=[('doing', 'Doing'), ('done', 'Done')], default='doing', max_length=6)),
                ('paid_client', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('parent_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket')),
            ],
        ),
    ]
