# Generated by Django 2.2.6 on 2019-11-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('todo', 'To-do'), ('doing', 'Doing'), ('done', 'Done'), ('backlog', 'Backlog')], default='todo', max_length=6),
        ),
    ]
