# Generated by Django 2.2.6 on 2019-10-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='has_solution',
            field=models.BooleanField(default=False),
        ),
    ]
