# Generated by Django 2.2.3 on 2019-07-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='author',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='tags',
        ),
        migrations.AddField(
            model_name='ticket',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
