# Generated by Django 2.2.3 on 2019-07-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tags',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
