# Generated by Django 2.2.3 on 2019-07-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20190726_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
