# Generated by Django 2.2.3 on 2019-07-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20190730_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='prority_level',
            field=models.CharField(blank='l', choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High')], max_length=1),
        ),
    ]
