# Generated by Django 2.2.3 on 2019-07-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20190728_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
