# Generated by Django 2.2.6 on 2019-11-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20191107_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
