# Generated by Django 2.2.3 on 2019-07-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status_open',
            field=models.BooleanField(default=True),
        ),
    ]
