# Generated by Django 2.2.3 on 2019-07-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_status_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status_open',
            field=models.BooleanField(blank=True),
        ),
    ]
