# Generated by Django 2.2.3 on 2019-07-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20190730_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='prority_level',
            field=models.CharField(choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High')], max_length=1),
        ),
    ]
