# Generated by Django 2.2.3 on 2019-07-31 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20190731_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='prority_level',
            new_name='prority',
        ),
    ]
