# Generated by Django 2.2.3 on 2019-07-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20190731_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='prority',
            field=models.CharField(choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High')], max_length=6),
        ),
    ]
