# Generated by Django 2.2.3 on 2019-07-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20190724_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status_open',
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
