# Generated by Django 2.2.3 on 2019-07-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20190731_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='prority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=6),
        ),
    ]
