# Generated by Django 2.2.6 on 2019-10-09 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticketsolution_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketsolution',
            old_name='ticket',
            new_name='parent',
        ),
    ]
