# Generated by Django 2.2.3 on 2019-07-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20190724_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='prority_level',
            field=models.CharField(default='Low', max_length=10),
        ),
    ]
