# Generated by Django 2.2.3 on 2019-07-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20190731_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='prority',
        ),
        migrations.AddField(
            model_name='ticket',
            name='prority_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=6),
        ),
    ]
